[package]
name = "camdrop"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
eframe = { version = "0.35.0", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
nom-exif = "3.8.0"
rfd = "0.17.2"
sysinfo = "0.38.4"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.27.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

